name: deep_pick
description: Simplifies manual JSON parsing with a type-safe API. No dynamic, no manual casting. Flexible inputs types, fixed output types. Useful parsing error messages
version: 0.7.1-pre.1
homepage: https://github.com/passsy/deep_pick

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  http: ^0.13.0
  lint: ^1.5.1
  test: ^1.16.0-0
