name: deep_pick
description: A library to access deep nested values inside of dart data structures, like returned from `dynamic jsonDecode(String source)`.
version: 0.1.1
homepage: https://github.com/passsy/deep_pick
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
